server:
  port: 31001
  servlet:
    context-path: /cms
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms
logging.level.org.springframework.boot.autoconfigure: ERROR